### ISSUE TITLE
Claims are kinda small

### ISSUE THREAD

**Issue by TheMprs** [scalda/Pub_server#7]
Hi man, first of all fantastic work on the server, second of all i wanted to ask if you could make the claim max block count bigger as it's only 2,600 which is not a lot, if id like to make another house or even a house in spawn I wouldn't have the space to do it, so please consider expanding it to 5,600 or any other amount you deem just. 

Thank you in advance
Mprs

**Comment by scalda** [comment]
2560 is the max we are allowing people to gain for free that is enough for
10 chunks worth. If you want more you will have to purchase them via the
shop.iskall85.com but please make sure you are online in the survival world
when you do it

**Comment by scalda** [comment]
considering this closed
